MSG_CLIENT_IDENTIFY             = 0
MSG_CLIENT_LOOKUP_TABLET        = 1
MSG_SERVER_LOOKUP_TABLET_RESP   = 2
MSG_CLIENT_SUBMIT_ISSUE         = 3
MSG_CLIENT_GET_ALL_TABLETS      = 4
MSG_SERVER_GET_ALL_TABLETS_RESP = 5
MSG_CLIENT_GET_ALL_USERS        = 6
MSG_SERVER_GET_ALL_USERS_RESP   = 7

CLIENT_UNIDENTIFIED     = 0
CLIENT_NET_ASSISTANT    = 1
CLIENT_STUDENT          = 2
