MSG_CLIENT_IDENTIFY             = 0
MSG_CLIENT_LOOKUP_TABLET        = 1
MSG_SERVER_LOOKUP_TABLET_RESP   = 2
MSG_CLIENT_SUBMIT_ISSUE         = 3

CLIENT_UNIDENTIFIED     = 0
CLIENT_NET_ASSISTANT    = 1
CLIENT_STUDENT          = 2
