# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'client_issuereport.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(908, 644)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.nameTextBox = QtWidgets.QLineEdit(self.groupBox_2)
        self.nameTextBox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nameTextBox.sizePolicy().hasHeightForWidth())
        self.nameTextBox.setSizePolicy(sizePolicy)
        self.nameTextBox.setObjectName("nameTextBox")
        self.verticalLayout_3.addWidget(self.nameTextBox)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.gradeTextBox = QtWidgets.QLineEdit(self.groupBox_2)
        self.gradeTextBox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gradeTextBox.sizePolicy().hasHeightForWidth())
        self.gradeTextBox.setSizePolicy(sizePolicy)
        self.gradeTextBox.setObjectName("gradeTextBox")
        self.verticalLayout_3.addWidget(self.gradeTextBox)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.gridLayout_5.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setScaledContents(False)
        self.label.setIndent(-1)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.pcsbTagTextBox = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pcsbTagTextBox.sizePolicy().hasHeightForWidth())
        self.pcsbTagTextBox.setSizePolicy(sizePolicy)
        self.pcsbTagTextBox.setObjectName("pcsbTagTextBox")
        self.verticalLayout_2.addWidget(self.pcsbTagTextBox)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setScaledContents(False)
        self.label_2.setIndent(-1)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.serialNoTextBox = QtWidgets.QLineEdit(self.groupBox)
        self.serialNoTextBox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.serialNoTextBox.sizePolicy().hasHeightForWidth())
        self.serialNoTextBox.setSizePolicy(sizePolicy)
        self.serialNoTextBox.setObjectName("serialNoTextBox")
        self.verticalLayout_2.addWidget(self.serialNoTextBox)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setScaledContents(False)
        self.label_3.setIndent(-1)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.deviceModelTextBox = QtWidgets.QLineEdit(self.groupBox)
        self.deviceModelTextBox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deviceModelTextBox.sizePolicy().hasHeightForWidth())
        self.deviceModelTextBox.setSizePolicy(sizePolicy)
        self.deviceModelTextBox.setObjectName("deviceModelTextBox")
        self.verticalLayout_2.addWidget(self.deviceModelTextBox)
        self.gridLayout_4.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.dateEntry = QtWidgets.QDateEdit(self.groupBox_3)
        self.dateEntry.setEnabled(False)
        self.dateEntry.setObjectName("dateEntry")
        self.gridLayout_6.addWidget(self.dateEntry, 3, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_6.addWidget(self.label_8, 2, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_6.addWidget(self.label_7, 5, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_6.addWidget(self.label_6, 0, 0, 1, 1)
        self.descTextEntry = QtWidgets.QTextEdit(self.groupBox_3)
        self.descTextEntry.setEnabled(False)
        self.descTextEntry.setObjectName("descTextEntry")
        self.gridLayout_6.addWidget(self.descTextEntry, 1, 0, 1, 1)
        self.problemsTextEntry = QtWidgets.QTextEdit(self.groupBox_3)
        self.problemsTextEntry.setEnabled(False)
        self.problemsTextEntry.setObjectName("problemsTextEntry")
        self.gridLayout_6.addWidget(self.problemsTextEntry, 6, 0, 1, 1)
        self.submitBtn = QtWidgets.QPushButton(self.groupBox_3)
        self.submitBtn.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.submitBtn.sizePolicy().hasHeightForWidth())
        self.submitBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.submitBtn.setFont(font)
        self.submitBtn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.submitBtn.setAutoExclusive(False)
        self.submitBtn.setObjectName("submitBtn")
        self.gridLayout_6.addWidget(self.submitBtn, 7, 0, 1, 1, QtCore.Qt.AlignRight)
        self.gridLayout_5.addWidget(self.groupBox_3, 1, 0, 1, 2)
        self.horizontalLayout_3.addLayout(self.gridLayout_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Student Info"))
        self.label_4.setText(_translate("MainWindow", "Name"))
        self.label_5.setText(_translate("MainWindow", "Grade"))
        self.groupBox.setTitle(_translate("MainWindow", "Tablet Info"))
        self.label.setText(_translate("MainWindow", "PCSB Tag (Bar Code)"))
        self.label_2.setText(_translate("MainWindow", "Serial No."))
        self.label_3.setText(_translate("MainWindow", "Device Model"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Issue Report"))
        self.label_8.setText(_translate("MainWindow", "Date of Incident"))
        self.label_7.setText(_translate("MainWindow", "Problems?"))
        self.label_6.setText(_translate("MainWindow", "Description of Incident"))
        self.submitBtn.setText(_translate("MainWindow", "Submit"))
